# Decision Tree Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('/content/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

array([[1000025,       5,       1, ...,       3,       1,       1],
       [1002945,       5,       4, ...,       3,       2,       1],
       [1015425,       3,       1, ...,       3,       1,       1],
       ...,
       [ 888820,       5,      10, ...,       8,      10,       2],
       [ 897471,       4,       8, ...,      10,       6,       1],
       [ 897471,       4,       8, ...,      10,       4,       1]])

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-1.38219432,  0.91903747,  0.9407658 , ...,  2.22576767,
         2.27129602,  0.24623928],
       [ 0.03390689,  1.27578287, -0.04290763, ...,  1.82407819,
         1.94996317,  3.74830911],
       [ 0.22797663,  1.27578287,  2.25233038, ...,  2.62745714,
         2.27129602, -0.33743902],
       ...,
       [ 0.16939025, -1.22143494, -0.69868992, ..., -0.98774815,
        -0.62069958, -0.33743902],
       [ 0.29888258, -0.50794414, -0.69868992, ..., -0.58605867,
        -0.62069958, -0.33743902],
       [-1.04129794,  1.98927367,  1.92443923, ...,  1.42238871,
         1.30729749, -0.33743902]])

## Training the Decision Tree Classification model on the Training set

In [5]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[103   4]
 [  3  61]]


0.9590643274853801

The variable classifier represents your trained machine learning model (e.g., a classification algorithm like a decision tree, random forest, logistic regression, etc.).
X_test contains the feature values of the test dataset. The model uses these features to make predictions.
y_pred stores the predicted labels (classifications) made by the model for the test dataset.


In Leman terms, we are training model using X_train and y_train , simply X_train are like problems you are solving and explaining model that by solving problems we got answers(y_train) now you are giving home work to model to work on new problems X_test... model tries to finish that homework and solve those and get answers called(y_pred) now we are tallying answers that model got(y_pred) with the key answer sheet you have (y_test) and giving marks to it (ex:accuracy)
